[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "next"
  port = 9999
  autoLaunch = false

[build]
  command = "cp ../../config.json ./config.json && next build"
  publish = "out"

[functions."process-task"]
  timeout = 60

[functions."chat"]
  timeout = 120

[functions."update-market-data"]
  timeout = 60

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/tts"
  to = "/.netlify/functions/tts"
  status = 200
